# Generated by Django 5.0.2 on 2025-09-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(choices=[('online', 'オンライン'), ('offline', 'オフライン')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personal_seminar',
            },
        ),
        migrations.CreateModel(
            name='PreparationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'preparation_template',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.IntegerField(help_text='開催日の何日前に通知するか')),
                ('integrations', models.ManyToManyField(blank=True, help_text='この通知設定で使用する外部連携（複数可。未指定時はアプリ共通設定を使用）', related_name='notification_settings', to='account.externalintegration')),
            ],
            options={
                'db_table': 'notification_setting',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='seminar.personalseminar')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='PersonalSeminarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='seminar.personalseminar')),
            ],
            options={
                'db_table': 'personal_seminar_date',
            },
        ),
        migrations.CreateModel(
            name='PreparationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deadline', models.DateField(db_index=True)),
                ('assignee', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_done', models.BooleanField(db_index=True, default=False)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='seminar.personalseminar')),
            ],
            options={
                'db_table': 'preparation_task',
            },
        ),
        migrations.CreateModel(
            name='PreparationTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relative_days_before', models.IntegerField(blank=True, null=True)),
                ('default_assignee', models.CharField(blank=True, max_length=100)),
                ('default_notes', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='seminar.preparationtemplate')),
            ],
            options={
                'db_table': 'preparation_task_template',
                'ordering': ['id'],
            },
        ),
    ]
