# Generated by Django 5.0.2 on 2024-03-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('host', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('japanese_name', models.CharField(default='', max_length=255)),
                ('is_japanese_site', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('japanese_title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('japanese_content', models.CharField(default='', max_length=255)),
                ('shown', models.BooleanField(default=True)),
                ('is_scraped', models.BooleanField(default=False)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newssource')),
            ],
        ),
    ]
