# Generated by Django 5.0.2 on 2024-04-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
