# Generated by Django 5.0.2 on 2024-04-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
