# Generated by Django 5.0.2 on 2024-04-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('japanese_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='newssource',
            name='regions',
            field=models.ManyToManyField(to='news.region'),
        ),
    ]
