# Generated by Django 5.0.2 on 2025-09-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('slack', 'Slack'), ('x', 'X (Twitter)')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_integration',
                'ordering': ['provider', 'name'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='external_in_provide_9d5436_idx')],
            },
        ),
    ]
